# Generated by Django 4.2.4 on 2023-08-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingclient_options_mailinglog_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Клиент'),
        ),
    ]
